version: "3.9"

services:
  mysql:
    image: mysql:8.4
    container_name: bloodbank-mysql

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: bloodbank-backend

    depends_on:
      - mysql

    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      PLAY_HTTP_SECRET_KEY: ${PLAY_HTTP_SECRET_KEY}
      JWT_SECRET: ${JWT_SECRET}

    ports:
      - "9000:9000"

  frontend:
    build: ./frontend
    container_name: bloodbank-frontend

    depends_on:
      - backend

    ports:
      - "3000:80"

volumes:
  mysql_data: