# This is the main configuration file for the application.
# https://www.playframework.com/documentation/latest/ConfigFile

#Cross server
play.filters.disabled += play.filters.csrf.CSRFFilter

#CORS
play.filters.enabled += play.filters.cors.CORSFilter

play.filters.hosts {
  allowed = ["."]
}

#db config
db.default.driver=com.mysql.cj.jdbc.Driver
#db.default.url="jdbc:mysql://localhost:3306/bloodbank_ebean"
#db.default.username="root"
#db.default.password="Mudit#12"

db.default.url=${?DB_URL}
db.default.username=${?DB_USERNAME}
db.default.password=${?DB_PASSWORD}

ebean.default = ["models.*"]

play.http.secret.key = ${?PLAY_HTTP_SECRET_KEY}

play.evolutions.db.default.autoApply = true